name: Ghost Development server

on:
  push:
    branches:
    - version9

jobs:
  build:
    # using Ubuntu
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1 #this installs node and npm for us
        with:
          node-version: "12.x"

      - uses: actions/cache@v1 # this allows for re-using node_modules caching, making builds a bit faster.
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - run: npm cache clean --force
      - run: npm install
      - run: npm audit fix --force
      - run: npm cache clean --force
      - run: npm install -g @angular/cli@9.1.13
      - run: nom ls -g --depth=0
      - run: ng build

      - name: copy file via ssh key
        uses: appleboy/scp-action@master
        env:
          HOST:  54.180.56.85
          USERNAME: ubuntu
          PORT:  22
          KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        with:
          source: "./dist"
          target: "/var/www/html/"
          strip_components: 2  
